<a href="https://colab.research.google.com/github/SAMMOSES26/task-7/blob/main/KNN_Assignment13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
#Social_Networks_Ads.csv

**Importing the libraries**

In [130]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np


In [131]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler ## standrard scalig
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score # import all the functions reqd for cross validation


**Importing the dataset**

In [132]:
df = pd.read_csv('Social_Network_Ads.csv')
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [133]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [134]:
df.dtypes

User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

In [135]:
df=df.drop_duplicates()

In [136]:
df.describe()

User ID         Age  EstimatedSalary   Purchased
count  4.000000e+02  400.000000       400.000000  400.000000
mean   1.569154e+07   37.655000     69742.500000    0.357500
std    7.165832e+04   10.482877     34096.960282    0.479864
min    1.556669e+07   18.000000     15000.000000    0.000000
25%    1.562676e+07   29.750000     43000.000000    0.000000
50%    1.569434e+07   37.000000     70000.000000    0.000000
75%    1.575036e+07   46.000000     88000.000000    1.000000
max    1.581524e+07   60.000000    150000.000000    1.000000

In [137]:
df = df.drop('User ID', axis=1)
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [138]:
iqr=df['Age'].quantile(0.75) - df['Age'].quantile(0.25)
upper_threshold=df['Age'].quantile(0.75) + (1.5 * iqr)
lower_threshold=df['Age'].quantile(0.25) - (1.5 * iqr)
upper_threshold,lower_threshold

(70.375, 5.375)

In [139]:
iqr=df['EstimatedSalary'].quantile(0.75) - df['EstimatedSalary'].quantile(0.25)
upper_threshold=df['EstimatedSalary'].quantile(0.75) + (1.5 * iqr)
lower_threshold=df['EstimatedSalary'].quantile(0.25) - (1.5 * iqr)
upper_threshold,lower_threshold

(155500.0, -24500.0)

In [140]:
# encode
dfT=df
dfT["Gender"] = df["Gender"].map({"Male" : 0, "Female" : 1})
# df['Gender'] = df['Gender'].map({"Male" : 0, "Female": 1})

In [141]:
dfT

Gender  Age  EstimatedSalary  Purchased
0         0   19            19000          0
1         0   35            20000          0
2         1   26            43000          0
3         1   27            57000          0
4         0   19            76000          0
..      ...  ...              ...        ...
395       1   46            41000          1
396       0   51            23000          1
397       1   50            20000          1
398       0   36            33000          0
399       1   49            36000          1

[400 rows x 4 columns]

**Splitting the dataset into the Training set and Test set**

In [142]:
X = dfT[['Gender','Age','EstimatedSalary']].values
y = dfT['Purchased'].values
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3)

**Feature Scaling**

In [143]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test) 

In [160]:
X_train


array([[ 0.94440028,  0.56031846, -0.93919505],
       [ 0.94440028, -0.07929958,  0.28352656],
       [ 0.94440028, -0.81029164,  0.372994  ],
       [ 0.94440028,  0.19482244, -0.312923  ],
       [ 0.94440028, -1.81540571, -0.79008265],
       [-1.05887304, -1.81540571, -0.55150283],
       [-1.05887304, -1.6326577 ,  0.46246143],
       [ 0.94440028,  0.74306647, -1.44617717],
       [-1.05887304, -0.62754362, -0.13398813],
       [-1.05887304, -0.2620476 , -0.93919505],
       [ 0.94440028,  1.01718849, -1.02866248],
       [ 0.94440028, -0.90166564, -0.46203539],
       [ 0.94440028,  0.83444048, -0.58132531],
       [-1.05887304,  1.01718849,  0.46246143],
       [-1.05887304, -0.53616962, -1.56546709],
       [-1.05887304,  1.38268452,  0.04494673],
       [ 0.94440028, -0.44479561, -0.58132531],
       [ 0.94440028,  0.74306647,  0.76068621],
       [-1.05887304, -0.07929958,  2.19216517],
       [-1.05887304, -0.99303965,  0.55192886],
       [-1.05887304, -1.08441366, -1.147

**Fitting K-NN to the Training set**

In [144]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier() # jus k=5 value randomly given by me not found by n-fold cross val
knn.fit(X_train,y_train)
# knn.score(x_test,y_test) #accuracy

KNeighborsClassifier()

In [145]:
for i in [1,2,3,4,5,6,7,8,9,10,20,50]:
  knn = KNeighborsClassifier(i) #initialising the model
  knn.fit(X_train,y_train) # training the model
  print("K value  : " , i, " train score : ", knn.score(X_train,y_train) , " cv score : ", np.mean(cross_val_score(knn, X_train, y_train, cv=10, scoring = "roc_auc"))) #predicting using the model


K value  :  1  train score :  1.0  cv score :  0.8299999999999998
K value  :  2  train score :  0.9142857142857143  cv score :  0.9033333333333333
K value  :  3  train score :  0.925  cv score :  0.913888888888889
K value  :  4  train score :  0.9035714285714286  cv score :  0.9305555555555557
K value  :  5  train score :  0.9107142857142857  cv score :  0.9327777777777777
K value  :  6  train score :  0.9071428571428571  cv score :  0.9283333333333333
K value  :  7  train score :  0.9071428571428571  cv score :  0.9252777777777779
K value  :  8  train score :  0.9071428571428571  cv score :  0.9319444444444445
K value  :  9  train score :  0.9107142857142857  cv score :  0.9399999999999998
K value  :  10  train score :  0.9107142857142857  cv score :  0.9391666666666666
K value  :  20  train score :  0.8964285714285715  cv score :  0.9488888888888889
K value  :  50  train score :  0.7857142857142857  cv score :  0.9419444444444445


**Predicting the Test set results**

In [148]:
y_pred=knn.predict(X_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0])

**Making the Confusion Matrix**

In [158]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[76,  1],
       [27, 16]])